# Output 输出
resolution = [1920, 1080]
fps = 60
sampleCount = 2
hardwareAccel = true
hevc = true
mpeg4 = false
# customEncoder = ""
fileNameFormat = "%date% %time% %info.name%_%level_prefix%"
ffmpegPreset = "medium p4 medium balanced" # "cpu nvenc qsv amf" or "any"
dynamicBitrateControl = true
bitrate = "26"
endingLength = 0.0
renderStartTime = 0.0
# renderEndTime = 
renderLoading = false


# Player 玩家
# playerAvatar = ""
playerName = "Dehou23333"
playerRks = 16.0
challengeColor = "rainbow" # white green blue red golden rainbow
challengeRank = 3


# Graphics 图像
# res_pack_path = ""
chartDebugLine = 0.0
chartDebugNote = 0.0
chartRatio = 1.0
noteScale = 1.0

renderLine = true
renderLineExtra = true
renderNote = true
doubleHint = true
renderUiPause = true
renderUiName = true
renderUiLevel = true
renderUiScore = true
renderUiCombo = true
renderUiBar = true
renderBg = true
renderBgDim = true
particle = true
renderExtra = true

aggressive = false
roman = false
chinese = false

bgBlurriness = 80.0
watermark = "Auto Rendered with Phi-Recorder. Only released by 德猴先生 on Bilibili."
combo = "AUTOPLAY"
maxParticles = 5000 # 5000 25000 200000

# Audio 音频
forceLimit = true
hires = false
loudnessEqualization = false
AudioMixOptimization = true

volumeMusic = 1.0
volumeSfx = 0.7
limitThreshold = 1.0 # if forceLimit
compressionRatio = 20.0 # else


# Other 其他
allGood = false
allBad = false
judgeOffset = 0.0
difficulty = ""
fade = 0.0
alphaTint = false

fxaa = false
speed = 1.0
